"""baseline existing schema

Revision ID: 35fdd1a81c22
Revises: 
Create Date: 2026-07-20 14:45:49.224739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35fdd1a81c22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('innovator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('funding_requirement', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('category', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dev_stage', sa.String(), nullable=True),
    sa.Column('idea_type', sa.String(), nullable=True),
    sa.Column('team_details', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_patented', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('pitch_deck_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['innovator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideas_innovator_id'), 'ideas', ['innovator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ideas_innovator_id'), table_name='ideas')
    op.drop_table('ideas')
    # ### end Alembic commands ###
