"""add deals table

Revision ID: 9b03ec305279
Revises: 09fb1fbe2dae
Create Date: 2026-07-23 10:39:19.495019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b03ec305279'
down_revision: Union[str, None] = '09fb1fbe2dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('sponsor_id', sa.UUID(), nullable=False),
    sa.Column('innovator_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('interested', 'in_discussion', 'term_sheet', 'funded', 'passed', name='dealstage'), nullable=False),
    sa.Column('offered_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('equity_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.ForeignKeyConstraint(['innovator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sponsor_id', 'idea_id', name='uq_sponsor_idea_deal')
    )
    op.create_index(op.f('ix_deals_idea_id'), 'deals', ['idea_id'], unique=False)
    op.create_index(op.f('ix_deals_innovator_id'), 'deals', ['innovator_id'], unique=False)
    op.create_index(op.f('ix_deals_sponsor_id'), 'deals', ['sponsor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_sponsor_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_innovator_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_idea_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
