"""add idea_likes table

Revision ID: f3298eec0688
Revises: dddc72290385
Create Date: 2026-07-20 19:48:28.744746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3298eec0688'
down_revision: Union[str, None] = 'dddc72290385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sponsor_id', sa.UUID(), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sponsor_id', 'idea_id', name='uq_sponsor_idea_like')
    )
    op.create_index(op.f('ix_idea_likes_idea_id'), 'idea_likes', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_likes_sponsor_id'), 'idea_likes', ['sponsor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_likes_sponsor_id'), table_name='idea_likes')
    op.drop_index(op.f('ix_idea_likes_idea_id'), table_name='idea_likes')
    op.drop_table('idea_likes')
    # ### end Alembic commands ###
